### ISSUE TITLE
Arc-Darker - Desktop contextual menu background color

### ISSUE THREAD

**Issue by lapega** [arc-design/arc-theme#270]
### Details

- Distribution: Ubuntu 18.04
- Desktop environment: gnome-shell 3.28.4
- Arc version/commit: 20190917+201909191216
- Murrine engine version: 0.98.2
- gnome-themes-extras version: 3.28
- Installation method: http://ppa.launchpad.net/fossfreedom/arc-gtk-theme-daily/ubuntu

------------------------------------------------------------

I'm using Arc-Darker, I love this variante, the only 'inconsistent' thing i found, is in the desktop contextual menu (right click), the menu background color is light, not dark. But the gnome shell menus are dark, so I would like to know how to change it.

I've upload an example:

![Captura de pantalla de 2019-09-24 11-23-52](https://user-images.githubusercontent.com/572502/65520372-d8438680-debd-11e9-9471-f8bf8ba5dfed.png)
![Captura de pantalla de 2019-09-24 11-23-20](https://user-images.githubusercontent.com/572502/65520374-d8438680-debd-11e9-82ff-7d5c2a0d7fbd.png)

**Comment by jnsh** [comment]
The desktop icons, and the background context menu are drawn by nautilus (i.e. the default Gnome/Ubuntu file manager). It's essentially styled just like any right-click menu on any other gtk3 application. There's probably no simple way to style the menu specifically for the nautilus desktop context.

Furthermore, the ability to draw desktop icons has been removed from nautilus 3.28, but I think Ubuntu still keeps shipping the older 3.26 version to retain the desktop icon support. On the other hand, Gnome has an semi-official shell-extension for desktop icons, that I think is in relatively good shape at this time (Gnome 3.34, although I haven't tested it myself). Either way, this issue isn't present in latest official Gnome desktop.

For the above reasons, and since it is a relatively minor visual inconsistency, I think this can be considered WONTFIX.

**Comment by lapega** [comment]
Oh, is good to know that is fixed in new versions.
Thank you!
